#!/usr/bin/env python

import sys
import os
import json

# Task: rmfile
# Description: Erases a file
def filerm(jsonStr):
    # Loading json string as a dictionary
    jsonDict = json.loads(jsonStr)

    # Loading variables from the json string
    filePath = jsonDict["filePath"]

    # CODE
    try os.remove(filePath):
        return u"{\"status\" : \"true\"}"
    except:
        return u"{\"status\" : \"false\"}"

# Function Execution
filerm(sys.argv[1])
