title = "Remove File"           # The task title
version = "0.1.0"             # Current version
authors = [ "Jarbas" ]        # Array with this task authors
date = 2016-05-27T17:08:00    # Curren version release date
categories = "action"         # Action or trigger
tags = [ "filesystem" ]             # Easier task search
min_jarbas_version = "0.1.0"  # Minimum Jarbas version required

# The programming language that this task need
[[languages]]
name = "python"
version = "2.7.11"

[[inputs]]
name = "filePath"
type = "file"
description = "File to de deleted"
mandatory = true

[[outputs]]
name = "status"
type = "boolean"
